// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG4Kf_XGo2hWffdLzY9hWIdLPuGXabgp0',
    appId: '1:718868725787:web:38c93d9184ad2c795db8be',
    messagingSenderId: '718868725787',
    projectId: 'smart-teacher-assistant-25',
    authDomain: 'smart-teacher-assistant-25.firebaseapp.com',
    databaseURL: 'https://smart-teacher-assistant-25-default-rtdb.firebaseio.com',
    storageBucket: 'smart-teacher-assistant-25.firebasestorage.app',
    measurementId: 'G-D2QJDKG45M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD516q3xQkRZ3lLjN_dDVCclnoQFzE4JI',
    appId: '1:718868725787:android:43a84fa0577dd42a5db8be',
    messagingSenderId: '718868725787',
    projectId: 'smart-teacher-assistant-25',
    databaseURL: 'https://smart-teacher-assistant-25-default-rtdb.firebaseio.com',
    storageBucket: 'smart-teacher-assistant-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Qvr1gMZF1_LRVImxWdPRNwhe2TgIMm0',
    appId: '1:718868725787:ios:d5f86e434555f7825db8be',
    messagingSenderId: '718868725787',
    projectId: 'smart-teacher-assistant-25',
    databaseURL: 'https://smart-teacher-assistant-25-default-rtdb.firebaseio.com',
    storageBucket: 'smart-teacher-assistant-25.firebasestorage.app',
    iosBundleId: 'com.integrafy.teacherAssistantFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Qvr1gMZF1_LRVImxWdPRNwhe2TgIMm0',
    appId: '1:718868725787:ios:d5f86e434555f7825db8be',
    messagingSenderId: '718868725787',
    projectId: 'smart-teacher-assistant-25',
    databaseURL: 'https://smart-teacher-assistant-25-default-rtdb.firebaseio.com',
    storageBucket: 'smart-teacher-assistant-25.firebasestorage.app',
    iosBundleId: 'com.integrafy.teacherAssistantFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG4Kf_XGo2hWffdLzY9hWIdLPuGXabgp0',
    appId: '1:718868725787:web:3be44e49d351966f5db8be',
    messagingSenderId: '718868725787',
    projectId: 'smart-teacher-assistant-25',
    authDomain: 'smart-teacher-assistant-25.firebaseapp.com',
    databaseURL: 'https://smart-teacher-assistant-25-default-rtdb.firebaseio.com',
    storageBucket: 'smart-teacher-assistant-25.firebasestorage.app',
    measurementId: 'G-8YJPG2V6XE',
  );
}
